"""empty message

Revision ID: f672aac2120e
Revises: dbc259cb04fa
Create Date: 2019-10-25 09:38:06.613916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f672aac2120e'
down_revision = 'dbc259cb04fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('_s_password', sa.String(length=256), nullable=True))
    op.drop_column('students', 's_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('s_password', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('students', '_s_password')
    # ### end Alembic commands ###
