"""empty message

Revision ID: 1211c2e7501c
Revises: 
Create Date: 2019-10-22 20:17:45.250562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1211c2e7501c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
