"""empty message

Revision ID: 72d126e81103
Revises: acd577de389d
Create Date: 2019-10-23 10:35:18.108687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d126e81103'
down_revision = 'acd577de389d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserModel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_name', sa.String(length=16), nullable=True),
    sa.Column('u_des', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_name')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('u_name', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('u_des', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('u_name', name='user_u_name_key')
    )
    op.drop_table('UserModel')
    # ### end Alembic commands ###
